### ISSUE TITLE
 AttributeError: module 'pyroute2' has no attribute 'NFTables'

### ISSUE THREAD

**Issue by jzofe** [blechschmidt/fakeroute#3]
line 270, in delete_firewall_rules
    with pyroute2.NFTables(nfgen_family=socket.AF_INET) as nft:
         ^^^^^^^^^^^^^^^^^
AttributeError: module 'pyroute2' has no attribute 'NFTables'

**Comment by blechschmidt** [comment]
6411932938a818abf1e3d2564d916b3dc7767927 fixes this.

**Comment by scriptkidsensei** [comment]
> [6411932](https://github.com/blechschmidt/fakeroute/commit/6411932938a818abf1e3d2564d916b3dc7767927) fixes this.

Hey! thank you for your answer, but I encountered a problem like this: 'TypeError: 'NoneType' object cannot be interpreted as an integer'
